export const MusicKeys = [
    {
      key: "Cmaj",
      chords: [
        { role: "1", name: "C", numeral: "I" },
        { role: "2m", name: "Dm", numeral: "ii" },
        { role: "3m", name: "Em", numeral: "iii" },
        { role: "4", name: "F", numeral: "IV" },
        { role: "5", name: "G", numeral: "V" },
        { role: "6m", name: "Am", numeral: "vi" },
        { role: "7dim", name: "Bdim", numeral: "viiº" },
      ],
    },
    {
      key: "Dbmaj",
      chords: [
        { role: "1", name: "Db", numeral: "I" },
        { role: "2m", name: "Ebm", numeral: "ii" },
        { role: "3m", name: "Fm", numeral: "iii" },
        { role: "4", name: "Gb", numeral: "IV" },
        { role: "5", name: "Ab", numeral: "V" },
        { role: "6m", name: "Bbm", numeral: "vi" },
        { role: "7dim", name: "Cdim", numeral: "viiº" },
      ],
    },
    {
      key: "Dmaj",
      chords: [
        { role: "1", name: "D", numeral: "I" },
        { role: "2m", name: "Em", numeral: "ii" },
        { role: "3m", name: "F#m", numeral: "iii" },
        { role: "4", name: "G", numeral: "IV" },
        { role: "5", name: "A", numeral: "V" },
        { role: "6m", name: "Bm", numeral: "vi" },
        { role: "7dim", name: "C#dim", numeral: "viiº" },
      ],
    },
    {
      key: "Ebmaj",
      chords: [
        { role: "1", name: "Eb", numeral: "I" },
        { role: "2m", name: "Fm", numeral: "ii" },
        { role: "3m", name: "Gm", numeral: "iii" },
        { role: "4", name: "Ab", numeral: "IV" },
        { role: "5", name: "Bb", numeral: "V" },
        { role: "6m", name: "Cm", numeral: "vi" },
        { role: "7dim", name: "Ddim", numeral: "viiº" },
      ],
    },
    {
      key: "Emaj",
      chords: [
        { role: "1", name: "E", numeral: "I" },
        { role: "2m", name: "F#m", numeral: "ii" },
        { role: "3m", name: "G#m", numeral: "iii" },
        { role: "4", name: "A", numeral: "IV" },
        { role: "5", name: "B", numeral: "V" },
        { role: "6m", name: "C#m", numeral: "vi" },
        { role: "7dim", name: "D#dim", numeral: "viiº" },
      ],
    },
    {
      key: "Fmaj",
      chords: [
        { role: "1", name: "F", numeral: "I" },
        { role: "2m", name: "Gm", numeral: "ii" },
        { role: "3m", name: "Am", numeral: "iii" },
        { role: "4", name: "Bb", numeral: "IV" },
        { role: "5", name: "C", numeral: "V" },
        { role: "6m", name: "Dm", numeral: "vi" },
        { role: "7dim", name: "Edim", numeral: "viiº" },
      ],
    },
    {
      key: "F#maj",
      chords: [
        { role: "1", name: "F#", numeral: "I" },
        { role: "2m", name: "G#m", numeral: "ii" },
        { role: "3m", name: "A#m", numeral: "iii" },
        { role: "4", name: "B", numeral: "IV" },
        { role: "5", name: "C#", numeral: "V" },
        { role: "6m", name: "Dm", numeral: "vi" },
        { role: "7dim", name: "Fdim", numeral: "viiº" },
      ],
    },
    {
      key: "Gmaj",
      chords: [
        { role: "1", name: "G", numeral: "I" },
        { role: "2m", name: "Am", numeral: "ii" },
        { role: "3m", name: "Bm", numeral: "iii" },
        { role: "4", name: "C", numeral: "IV" },
        { role: "5", name: "D", numeral: "V" },
        { role: "6m", name: "Em", numeral: "vi" },
        { role: "7dim", name: "F#dim", numeral: "viiº" },
      ],
    },
    {
      key: "Abmaj",
      chords: [
        { role: "1", name: "Ab", numeral: "I" },
        { role: "2m", name: "Bbm", numeral: "ii" },
        { role: "3m", name: "Cm", numeral: "iii" },
        { role: "4", name: "Db", numeral: "IV" },
        { role: "5", name: "Eb", numeral: "V" },
        { role: "6m", name: "Fm", numeral: "vi" },
        { role: "7dim", name: "Gdim", numeral: "viiº" },
      ],
    },
    {
      key: "Amaj",
      chords: [
        { role: "1", name: "A", numeral: "I" },
        { role: "2m", name: "Bm", numeral: "ii" },
        { role: "3m", name: "C#m", numeral: "iii" },
        { role: "4", name: "D", numeral: "IV" },
        { role: "5", name: "E", numeral: "V" },
        { role: "6m", name: "F#m", numeral: "vi" },
        { role: "7dim", name: "G#dim", numeral: "viiº" },
      ],
    },
    {
      key: "Bbmaj",
      chords: [
        { role: "1", name: "Bb", numeral: "I" },
        { role: "2m", name: "Cm", numeral: "ii" },
        { role: "3m", name: "Dm", numeral: "iii" },
        { role: "4", name: "Eb", numeral: "IV" },
        { role: "5", name: "F", numeral: "V" },
        { role: "6m", name: "Gm", numeral: "vi" },
        { role: "7dim", name: "Adim", numeral: "viiº" },
      ],
    },
    {
      key: "Bmaj",
      chords: [
        { role: "1", name: "B", numeral: "I" },
        { role: "2m", name: "C#m", numeral: "ii" },
        { role: "3m", name: "D#m", numeral: "iii" },
        { role: "4", name: "E", numeral: "IV" },
        { role: "5", name: "F#", numeral: "V" },
        { role: "6m", name: "G#m", numeral: "vi" },
        { role: "7dim", name: "A#dim", numeral: "viiº" },
      ],
    },
  
  ];