export const MusicKeys = [
    {
      key: "C",
      chords: [
        { role: "1", name: "C", numeral: "I" },
        { role: "2m", name: "Dm", numeral: "ii" },
        { role: "3m", name: "Em", numeral: "iii" },
        { role: "4", name: "F", numeral: "IV" },
        { role: "5", name: "G", numeral: "V" },
        { role: "6m", name: "Am", numeral: "vi" },
        { role: "7º", name: "Bº", numeral: "viiº" },
      ],
    },
    {
      key: "Db",
      chords: [
        { role: "1", name: "Db", numeral: "I" },
        { role: "2m", name: "Ebm", numeral: "ii" },
        { role: "3m", name: "Fm", numeral: "iii" },
        { role: "4", name: "Gb", numeral: "IV" },
        { role: "5", name: "Ab", numeral: "V" },
        { role: "6m", name: "Bbm", numeral: "vi" },
        { role: "7º", name: "Cº", numeral: "viiº" },
      ],
    },
    {
      key: "D",
      chords: [
        { role: "1", name: "D", numeral: "I" },
        { role: "2m", name: "Em", numeral: "ii" },
        { role: "3m", name: "F#m", numeral: "iii" },
        { role: "4", name: "G", numeral: "IV" },
        { role: "5", name: "A", numeral: "V" },
        { role: "6m", name: "Bm", numeral: "vi" },
        { role: "7º", name: "C#º", numeral: "viiº" },
      ],
    },
    {
      key: "Eb",
      chords: [
        { role: "1", name: "Eb", numeral: "I" },
        { role: "2m", name: "Fm", numeral: "ii" },
        { role: "3m", name: "Gm", numeral: "iii" },
        { role: "4", name: "Ab", numeral: "IV" },
        { role: "5", name: "Bb", numeral: "V" },
        { role: "6m", name: "Cm", numeral: "vi" },
        { role: "7º", name: "Dº", numeral: "viiº" },
      ],
    },
    {
      key: "E",
      chords: [
        { role: "1", name: "E", numeral: "I" },
        { role: "2m", name: "F#m", numeral: "ii" },
        { role: "3m", name: "G#m", numeral: "iii" },
        { role: "4", name: "A", numeral: "IV" },
        { role: "5", name: "B", numeral: "V" },
        { role: "6m", name: "C#m", numeral: "vi" },
        { role: "7º", name: "D#º", numeral: "viiº" },
      ],
    },
    {
      key: "F",
      chords: [
        { role: "1", name: "F", numeral: "I" },
        { role: "2m", name: "Gm", numeral: "ii" },
        { role: "3m", name: "Am", numeral: "iii" },
        { role: "4", name: "Bb", numeral: "IV" },
        { role: "5", name: "C", numeral: "V" },
        { role: "6m", name: "Dm", numeral: "vi" },
        { role: "7º", name: "Eº", numeral: "viiº" },
      ],
    },
    {
      key: "F#",
      chords: [
        { role: "1", name: "F#", numeral: "I" },
        { role: "2m", name: "G#m", numeral: "ii" },
        { role: "3m", name: "A#m", numeral: "iii" },
        { role: "4", name: "B", numeral: "IV" },
        { role: "5", name: "C#", numeral: "V" },
        { role: "6m", name: "Dm", numeral: "vi" },
        { role: "7º", name: "Fº", numeral: "viiº" },
      ],
    },
    {
      key: "G",
      chords: [
        { role: "1", name: "G", numeral: "I" },
        { role: "2m", name: "Am", numeral: "ii" },
        { role: "3m", name: "Bm", numeral: "iii" },
        { role: "4", name: "C", numeral: "IV" },
        { role: "5", name: "D", numeral: "V" },
        { role: "6m", name: "Em", numeral: "vi" },
        { role: "7º", name: "F#º", numeral: "viiº" },
      ],
    },
    {
      key: "Ab",
      chords: [
        { role: "1", name: "Ab", numeral: "I" },
        { role: "2m", name: "Bbm", numeral: "ii" },
        { role: "3m", name: "Cm", numeral: "iii" },
        { role: "4", name: "Db", numeral: "IV" },
        { role: "5", name: "Eb", numeral: "V" },
        { role: "6m", name: "Fm", numeral: "vi" },
        { role: "7º", name: "Gº", numeral: "viiº" },
      ],
    },
    {
      key: "A",
      chords: [
        { role: "1", name: "A", numeral: "I" },
        { role: "2m", name: "Bm", numeral: "ii" },
        { role: "3m", name: "C#m", numeral: "iii" },
        { role: "4", name: "D", numeral: "IV" },
        { role: "5", name: "E", numeral: "V" },
        { role: "6m", name: "F#m", numeral: "vi" },
        { role: "7º", name: "G#º", numeral: "viiº" },
      ],
    },
    {
      key: "Bb",
      chords: [
        { role: "1", name: "Bb", numeral: "I" },
        { role: "2m", name: "Cm", numeral: "ii" },
        { role: "3m", name: "Dm", numeral: "iii" },
        { role: "4", name: "Eb", numeral: "IV" },
        { role: "5", name: "F", numeral: "V" },
        { role: "6m", name: "Gm", numeral: "vi" },
        { role: "7º", name: "Aº", numeral: "viiº" },
      ],
    },
    {
      key: "B",
      chords: [
        { role: "1", name: "B", numeral: "I" },
        { role: "2m", name: "C#m", numeral: "ii" },
        { role: "3m", name: "D#m", numeral: "iii" },
        { role: "4", name: "E", numeral: "IV" },
        { role: "5", name: "F#", numeral: "V" },
        { role: "6m", name: "G#m", numeral: "vi" },
        { role: "7º", name: "A#º", numeral: "viiº" },
      ],
    },
  
  ];